version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: RootPass*
      MYSQL_USER: develop
      MYSQL_PASSWORD: DevelopPass
      MYSQL_DATABASE: nrs_school
    volumes:
      - ./docker/setup.sql:/docker/docker-entrypoint-initdb.d/setup.sql
    container_name: db
