version: '3'
services:
  nrs_school:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "RootPass*"
      MYSQL_DATABASE: "NRS_SCHOOL"
      MYSQL_USER: "develop"
      MYSQL_PASSWORD: "DevelopPass"
