version: '3.4'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: DevelopPass
      POSTGRES_DB: NRS_SCHOOL
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - application-network

  nrs-school-java: 
    image: neresdev/nrs-school-java
    restart: always
    environment:  
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/NRS_SCHOOL
      SPRING_DATASOURCE_USERNAME: develop
      SPRING_DATASOURCE_PASSWORD: DevelopPass
      SPRING_PROFILE_ACTIVE: dev
    ports:
      - "8081:8081"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - application-network

networks:
    application-network:
      driver: bridge