version: '3.4'

services:
  db:
    image: mysql:8.3.0
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:  
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: develop
      MYSQL_PASSWORD: DevelopPass
      MYSQL_DATABASE: NRS_SCHOOL
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - 3308
    networks:
      - application-network

  nrs-school-java: 
    image: neresdev/nrs-school-java
    restart: always
    environment:  
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3308/NRS_SCHOOL?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: develop
      SPRING_DATASOURCE_PASSWORD: DevelopPass
      SPRING_PROFILE_ACTIVE: dev
    ports:
      - "8081:8081"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - application-network

networks:
    application-network:
      driver: bridge