CREATE USER 'develop'@'%' IDENTIFIED BY 'DevelopPass';

GRANT ALL PRIVILEGES ON NRS_SCHOOL.* TO 'develop'@'%';

USE NRS_SCHOOL;

CREATE TABLE STUDENT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
