CREATE DATABASE IF NOT EXISTS NRS_SCHOOL;

USE NRS_SCHOOL;

CREATE TABLE IF NOT EXISTS CLASSROOMS (
    IDT_CLASSROOM INT AUTO_INCREMENT NOT NULL,
    CLASS VARCHAR(3) NOT NULL,
    TEACHER VARCHAR(255) NOT NULL,
    SHIFT TINYINT NOT NULL,
    CLASS_NUMBER SMALLINT NOT NULL,
    PRIMARY KEY (IDT_CLASSROOM)
);

CREATE TABLE IF NOT EXISTS STUDENTS (
    IDT_STUDENT INT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    REGISTRATION VARCHAR(7) UNIQUE,
    PRIMARY KEY (IDT_STUDENT)

);



