version: '3'
services:
  nrs_school:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "develop"
      POSTGRES_PASSWORD: "DevelopPass"
      POSTGRES_DB: "NRS_SCHOOL"
