version: '3'
services:
  nrs_school:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "RootPass*"
      MYSQL_DATABASE: "NRS_SCHOOL"
      MYSQL_USER: "develop"
      MYSQL_PASSWORD: "DevelopPass"
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
volumes:
  redis-data: