-- ============================================================
-- Database initialization script for NRS School
-- Compatible with Neon PostgreSQL
-- Uses IF NOT EXISTS to safely handle re-runs
-- ============================================================

-- ----------------------------
-- Sequences
-- ----------------------------
CREATE SEQUENCE IF NOT EXISTS SQ_CLASSROOM_IDT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SQ_STUDENT_IDT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SQ_SUBJECT_IDT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SQ_STUDENT_RECOVERY_IDT START WITH 1 INCREMENT BY 1;

-- ----------------------------
-- USERS table
-- ----------------------------
CREATE TABLE IF NOT EXISTS USERS (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(255) NOT NULL,
    email       VARCHAR(100) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------
-- CLASSROOMS table
-- ----------------------------
CREATE TABLE IF NOT EXISTS CLASSROOMS (
    IDT_CLASSROOM       BIGINT PRIMARY KEY DEFAULT nextval('SQ_CLASSROOM_IDT'),
    CLASS_NAME          VARCHAR(255) NOT NULL,
    CAPACITY            INTEGER NOT NULL,
    TEACHER_NAME        VARCHAR(255) NOT NULL,
    SHIFT               INTEGER NOT NULL,
    CLASS_NUMBER        INTEGER NOT NULL,
    CLASSROOM_REF_CODE  UUID,
    CREATED_AT          TIMESTAMP,
    UPDATED_AT          TIMESTAMP
);

-- ----------------------------
-- STUDENTS table
-- ----------------------------
CREATE TABLE IF NOT EXISTS STUDENTS (
    IDT_STUDENT         BIGINT PRIMARY KEY DEFAULT nextval('SQ_STUDENT_IDT'),
    NAME                VARCHAR(255) NOT NULL,
    EMAIL               VARCHAR(255) NOT NULL UNIQUE,
    IDT_CLASSROOM       BIGINT,
    REGISTRATION        VARCHAR(7) UNIQUE,
    STUDENT_REF_CODE    UUID NOT NULL,
    CREATED_AT          TIMESTAMP,
    UPDATED_AT          TIMESTAMP
);

-- ----------------------------
-- SUBJECT table
-- ----------------------------
CREATE TABLE IF NOT EXISTS SUBJECT (
    IDT_SUBJECT          BIGINT PRIMARY KEY DEFAULT nextval('SQ_SUBJECT_IDT'),
    SUBJECT_DESCRIPTION  VARCHAR(30) NOT NULL
);

-- ----------------------------
-- STUDENTS_RECOVERY table
-- ----------------------------
CREATE TABLE IF NOT EXISTS STUDENTS_RECOVERY (
    IDT_STUDENT_RECOVERY  BIGINT PRIMARY KEY DEFAULT nextval('SQ_STUDENT_RECOVERY_IDT'),
    IDT_STUDENT           BIGINT NOT NULL,
    IDT_SUBJECT           BIGINT NOT NULL
);

-- ----------------------------
-- Foreign Key Constraints
-- (only added if they do not already exist)
-- ----------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_student_classroom'
    ) THEN
        ALTER TABLE STUDENTS
            ADD CONSTRAINT fk_student_classroom
            FOREIGN KEY (IDT_CLASSROOM) REFERENCES CLASSROOMS(IDT_CLASSROOM);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_recovery_student'
    ) THEN
        ALTER TABLE STUDENTS_RECOVERY
            ADD CONSTRAINT fk_recovery_student
            FOREIGN KEY (IDT_STUDENT) REFERENCES STUDENTS(IDT_STUDENT);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_recovery_subject'
    ) THEN
        ALTER TABLE STUDENTS_RECOVERY
            ADD CONSTRAINT fk_recovery_subject
            FOREIGN KEY (IDT_SUBJECT) REFERENCES SUBJECT(IDT_SUBJECT);
    END IF;
END $$;
